### ISSUE TITLE
Setting the character for dice templates only updates it in current category (in UI)

### ISSUE THREAD

**Issue by corinnaj** [cmfcmf/roc-and-roll#119]
Maybe supporting different characters for different categories could even be desired

**Comment by corinnaj** [comment]
Do we even still need the use case to select different characters, or should we always use the main character?

**Comment by tom95** [comment]
I would say we can drop it for now, OR change it to apply on a per dice-template basis, so you can create dice templates for specific characters. An unset character would then be the main character.

**Comment by corinnaj** [comment]
I would also tend to drop it for now, maybe making it an option per dice-template later on

**Comment by cmfcmf** [comment]
Seems good to me 👍
