### ISSUE TITLE
Remove token from initiative when it is deleted from the map

### ISSUE THREAD

**Issue by tom95** [cmfcmf/roc-and-roll#13]

**Comment by cmfcmf** [comment]
hmm, maybe open a popup and ask the user?

**Comment by s4pu** [comment]
I can't think of any case in which I would want the token in the initiative tracker and not on the map. And I would use popups sparingly.

**Comment by cmfcmf** [comment]
Hmm, what about when the user accidentally deletes their token?

**Comment by corinnaj** [comment]
I think if you have to readd your token to the scene, you can also readd it to the initiative. I think so far accidentally deleting tokens, has not really been an issue.

**Comment by cmfcmf** [comment]
Fair :)
