### ISSUE TITLE
Music upload allows any file type

### ISSUE THREAD

**Issue by corinnaj** [cmfcmf/roc-and-roll#34]

**Comment by cmfcmf** [comment]
The same is true for token image uploads. I think I accidentally uploaded my thesis as a token...

**Comment by s4pu** [comment]
+2 to Intelligence!

**Comment by cmfcmf** [comment]
Done as part of https://github.com/cmfcmf/roc-and-roll/commit/86f2878eb5ddd205b4c167b5c2ce80e5e0b67e2d
