### ISSUE TITLE
Map doesnt change when until I interact with the system again

### ISSUE THREAD

**Issue by tom95** [cmfcmf/roc-and-roll#54]
* click move here
* wait
* interact with the system, e.g. pan the map

**Comment by cmfcmf** [comment]
Fixed in https://github.com/cmfcmf/roc-and-roll/commit/9fce8ff6f0c9dbf5a48fb7a7b3f77823765d79bb

**Comment by cmfcmf** [comment]
And further fixes in https://github.com/cmfcmf/roc-and-roll/commit/86e30a4d7bb2c24674f598d853257f55c3575a9c
